### ISSUE TITLE
TinyMCE Embedded image - "edit image" fails to load form data

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#1137] opened 2020-09-14 04:38 UTC
# Issue

When embedding an image with a custom  dimension into a TinyMCE dialog, going back to "edit image" does not populate the current image dimensions until:
 - the form is clicked
 - keypress is performed

# Reproduction

- Insert an image into TinyMce with a custom dimension (e.g. 400 x 300)
- save the page
- select the image in the editor, select the "edit image" button.
- Observe that the "width" and "height" fields are blank.

![image](https://user-images.githubusercontent.com/936064/93044503-30643180-f6a9-11ea-9fec-9b395a61fdcc.png)

- press any key, click any field.
- notice the dimensions "pop" into the form

![image](https://user-images.githubusercontent.com/936064/93044539-3f4ae400-f6a9-11ea-94c6-75719bc2be3c.png)

# Versions

1.4.6 (asset admin)
4.4.7 (framework)
1.4.5 (admin)

Also:
4.7 (cms recipe)

# Notes
- In addition to the dimension values, the fields like Caption, Alternate Text and Title text works when you first edit the image and then Save it, the previous entry will not be shown again when you edit the image the second time.

**Comment by tractorcow** [comment] 2020-09-14 04:45
I bet it's some really obscure react coding issue with initial state not being set properly.

**Comment by GuySartorelli** [comment] 2021-02-22 21:19
Note also that when this _does_ populate, it populates with some default values rather than with the values that had been previously saved. This is also true of the alignment.
Let me know if that's considered a separate bug but I think it's the same thing (and increases the impact considerably)

**Comment by brynwhyman** [comment] 2021-05-04 21:41
It appears that this affects any data on the form, including placement, alt text, etc. I'll update the title to reflect that.

**Comment by TomOudeRengerink** [comment] 2021-05-31 09:38
Any updates on this yet?

**Comment by brynwhyman** [comment] 2021-06-01 03:48
This looks to be a duplicate of: https://github.com/silverstripe/silverstripe-assets/issues/131

I'll close this issue in favour of the above which references some prior work attempting to resolve this.

**Closed by brynwhyman** 2021-06-01 03:48 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug

**Comment by brynwhyman** [comment] 2021-06-24 02:44
As mentioned in https://github.com/silverstripe/silverstripe-assets/issues/131

This has been fixed in 1.7.x and 1.8.x of silverstripe/asset-admin. See: silverstripe/silverstripe-asset-admin#1213

Just discussing doing patch releases of each branch now.
