### ISSUE TITLE
Not clear that files are now protected by default

### ISSUE THREAD

**Issue by axyr** [silverstripe/silverstripe-asset-admin#161] opened 2016-05-12 06:54 UTC
## Acceptance criteria

 * It's clear whether a files is draft, published, modified
 * The domain model matches that of pages
 * Insert media selects from draft items

Excluded

 * delete-from-draft support: we'll clarify this as part of "campaign feature complete"

Tasks

 - [x] Add marker for Gallery items that are draft or modified
 - [x] Clarify Protected status and determine whether that needs visual representation
 - [x] Add marker for Files in Editor

----

Notes

 * This might cause #160 ?

 * [Design UX patterns for deleting files and folders](https://github.com/silverstripe/silverstripe-asset-admin/issues/219)

**Comment by tractorcow** [comment] 2016-05-20 05:25
We need to have some kind of indicator on files; This information should include:
- Published state (live, draft only, changed, etc).
- Protected state (public / protected)

**Comment by chillu** [comment] 2016-08-18 03:46
Closing as duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/219 (we'll need to identify what needs fixing from a UX perspective first)

**Comment by chillu** [comment] 2016-08-18 03:47
Actually, reopening since this issue is marked against alpha2 (and of a smaller scope), and https://github.com/silverstripe/silverstripe-asset-admin/issues/219 is marked against beta1 with a larger scope.

**Comment by flamerohr** [comment] 2016-10-04 08:02
Pull requests:
https://github.com/silverstripe/silverstripe-framework/pull/6136
https://github.com/silverstripe/silverstripe-asset-admin/pull/284

**Comment by tractorcow** [comment] 2016-10-05 02:08
I've done my peer review, and added https://github.com/silverstripe/silverstripe-cms/pull/1637 to the list of pull requests.

**Comment by tractorcow** [comment] 2016-10-06 05:10
Closed with https://github.com/silverstripe/silverstripe-asset-admin/pull/284

**Closed by tractorcow** 2016-10-06 05:10 UTC
Labels: affects/v4, type/enhancement
