### ISSUE TITLE
SS 4.3 AssetAdmin does not work with PHP 7.3

### ISSUE THREAD

**Issue by brokemeisteratwork** [silverstripe/silverstripe-asset-admin#897] opened 2018-12-26 22:14 UTC
The AssetAdmin does not load with PHP 7.3 due to this issue:
[silverstripe/silverstripe-graphql/issues/197]

```
Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ...\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php on line 275, referer: http://localhost/admin/assets/
Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ...\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php on line 287, referer: http://localhost/admin/assets/
Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ...\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php on line 300, referer: http://localhost/admin/assets/
Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ...\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php on line 307, referer: http://localhost/admin/assets/
```

Reproduction Using PHP 7.3.:
- Installation of SS 4.3 with Composer
- Call AssetAdmin in Backend

**Comment by robbieaverill** [comment] 2018-12-26 22:16
Thanks for raising the issue. Let’s track this as a duplicate of https://github.com/silverstripe/silverstripe-graphql/issues/197

**Closed by robbieaverill** 2018-12-26 22:16 UTC
