### ISSUE TITLE
File permission labels show "undefined"

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-asset-admin#955] opened 2019-06-11 02:59 UTC
**SS 4.4.0** via CWP 2.3.0-rc2

![image](https://user-images.githubusercontent.com/5170590/59240864-8e5dca00-8c59-11e9-925e-ceda6b2217a0.png)

**Comment by chillu** [comment] 2019-06-11 03:15
Marking as "impact high" since it's a pretty common UI area and looks very unprofessional

**Comment by dnsl48** [comment] 2019-06-12 05:31
this is a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/938 and has been [fixed](https://github.com/silverstripe/silverstripe-admin/pull/879) in 4.4.1

**Closed by dnsl48** 2019-06-12 05:31 UTC
Labels: affects/v4, change/patch, effort/easy, impact/high, type/UX, type/bug
