### ISSUE TITLE
Sort menu throws javascript error

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-asset-admin#959] opened 2019-06-20 19:34 UTC
Choosing any item from the assets sort menu throws an error in the JS console.

Error thrown:

TypeError: undefined is not an object (evaluating '_.ReactTestUtils.Simulate')
at bundle.js 1:116321

Version info:

silverstripe/asset-admin                  1.4.1
silverstripe/assets                       1.4.1
silverstripe/recipe-cms                   4.4.1

# Pulls request
* [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/966

**Comment by maxime-rainville** [comment] 2019-07-13 13:52
Changed the title to reflect the fact that sorting of files doesn't work because of this UI bug.

I think the problem is coming from this line https://github.com/silverstripe/silverstripe-asset-admin/blob/48c072ff3c11e847f1b440d2b06852cf711da7d9/client/src/containers/Gallery/Gallery.js#L338

If I comment out that line I don't get an error ... but I don't get any sorting either. The comment on the line says that: `Chosen stops the change event from reaching React so we have to simulate a click.`

My guess is that `ReactTestUtils` isn't bundle in with our built library ... because it's meant to be a test utility.

**Comment by maxime-rainville** [comment] 2019-07-13 13:55
Fixed by https://github.com/silverstripe/silverstripe-asset-admin/pull/966

**Closed** 2019-07-14 22:34 UTC
Labels: affects/v4, effort/easy, impact/high, type/bug
