### ISSUE TITLE
Broken screen whes session has expired

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-asset-admin#1217] opened 2021-06-23 04:31 UTC
If you try navigating the the asset-admin area with an expired session, you get a mangled error.
![image](https://user-images.githubusercontent.com/1168676/123035960-5e4c8280-d440-11eb-99cb-51d7d9974472.png)

**Comment by brynwhyman** [comment] 2021-06-24 22:10
Duplicate of: https://github.com/silverstripe/silverstripe-asset-admin/issues/1006

**Closed by brynwhyman** 2021-06-24 22:10 UTC
Labels: affects/v4, impact/medium, type/bug
