### ISSUE TITLE
Editor form loading blocks on history API ajax request

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#538] opened 2017-07-07 01:32 UTC
The form is loaded, but locked and uneditable until the `admin/assets/api/history` is loaded.

It would be better if the panel didn't load at all until clicked on, and the loading was limited to that panel.

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/171
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/565

**Comment by tractorcow** [comment] 2017-07-07 01:34
![image](https://user-images.githubusercontent.com/936064/27939455-df2a3020-6318-11e7-8257-76325bc840b6.png)

**Comment by chillu** [comment] 2017-07-10 20:20
I see this as a high priority since it actually make the whole UI feel sluggish on a major user action.

**Comment by clarkepaul** [comment] 2017-07-10 21:52
I take  it this isn't anything for me to worry about UX wise.

**Comment by chillu** [comment] 2017-07-10 22:19
@clarkepaul said that we should move the "history" tab into a secondary action anyway, because it needs different form actions (revert). Paul, can you please link the other issue here

**Comment by clarkepaul** [comment] 2017-07-10 22:46
The moving of file history issue https://github.com/silverstripe/silverstripe-asset-admin/issues/541 which should probably happen first.

**Comment by flamerohr** [comment] 2017-07-26 00:30
This seems to be a few things stacked up to give this experience:
* a history request is made before the form data request in certain circumstances
* Apache delays the important form data request until the history request is completed (what you observe in the screenshot)
* a history request could be made on unloading the old history list, un-intentional side-effect of having a `oldFileId !== newFileId` check.

To reproduce: open a file in editor, open different file, open the first file. This is all without closing the Editor.

**Closed** 2017-07-31 22:54 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/bug, type/UX
