### ISSUE TITLE
Zooming out in Google Chrome hides the text in the asset manager 

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-asset-admin#1184] opened 2021-03-11 21:10 UTC
1. load /admin/assets/
2. put zoom in chrome to 90% (or smaller)
3. can't see text

![image](https://user-images.githubusercontent.com/67215/110854467-e12a5100-8319-11eb-9cfc-9a7292e022b3.png)

tested on windows

**Comment by kinglozzer** [comment] 2021-03-11 21:40
Duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/1147

**Closed by kinglozzer** 2021-03-11 21:40 UTC
