### ISSUE TITLE
BUG PopoverField generates invalid html (nested button tags)

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#774] opened 2018-04-18 05:39 UTC
Original issue https://github.com/silverstripe/silverstripe-asset-admin/issues/749

This issue was originally introduced with https://github.com/silverstripe/silverstripe-admin/pull/459, however this violates w3c html standards by having nested button tag. This results in lots of weird and unpredictable behaviour.

E.g. https://github.com/silverstripe/silverstripe-campaign-admin/pull/97 breaks because the `Remove` button breaks when nested inside two `<button>` tags.

We originally attempted to fix this with https://github.com/silverstripe/silverstripe-admin/pull/470, but it didn't fix the core issue.

# Tasks:

 - Revert https://github.com/silverstripe/silverstripe-admin/pull/470
 - Revert https://github.com/silverstripe/silverstripe-admin/pull/459
 - Find another solution to "tab" key accessibility described by https://github.com/silverstripe/silverstripe-admin/pull/459

# Pull Requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/499
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/501

**Comment by tractorcow** [comment] 2018-04-18 05:45
Suggest something like switching from

```
<button>
  <button />
</button>
```

to

```
<div>
  <button />
  <button />
</div>
```

**Comment by flamerohr** [comment] 2018-04-18 08:45
you're going to break styling things like button groups with that container logic...

it's a shame you're not able to use `<React.Fragment>` which is available from React `16.2` onwards, as it would solve both issues cleanly

**Comment by flamerohr** [comment] 2018-04-18 08:48
Another option is to move the styling to the container div and make that div look like a button (with the generic `btn` class from bootstrap)
Then have a transparent button cover the entire container div.

This is all a bit hacky, but like I mentioned `<React.Fragment>` would be the way to go when it's available.

**Comment by tractorcow** [comment] 2018-04-18 22:15
Yeah that last solution would be fine I guess. :)

**Comment by maxime-rainville** [comment] 2018-04-26 04:44
@tractorcow found an issue ... https://github.com/silverstripe/silverstripe-admin/pull/499/files#r184267667

**Comment by tractorcow** [comment] 2018-04-26 06:00
Followup fix at https://github.com/silverstripe/silverstripe-admin/pull/501

**Comment by unclecheese** [comment] 2018-05-02 00:14
### Are we really fixing the right problem?

@newleeland  and @clarkepaul have asked for clarity on what the issue is, and after explaining it to them, they've expressed their concern that these popovers should have been dropdowns from day one, which is the best practice for accessibility. The popovers were being used as a hack to get the original story over the line many months ago, because of some unknown issue with `react-bootstrap.` Since then, they've advocated ending the improper use of popovers as dropdowns, as it is this misappropriation that is causing the accessibility problems, not the way that we're hacking popovers to be more like dropdowns.

We need to investigate how we can implement the correct fix, and start using proper dropdown buttons. Perhaps the upgrade `reactstrap` solved whatever that issue was? Either way, it is their opinion that we shouldn't be continuing to add technical debt to this problem.

### Suggestion

We either repurpose this ticket, or close it and create a new one for changing these popovers to dropdowns.

**Comment by tractorcow** [comment] 2018-05-02 05:16
Actually I think that's a better approach. We just need to make sure we properly support dropdown as form action container. This means looking for the form action name as a value of a field instead of a field name. This should work on frontend forms as well as backend.

**Comment by tractorcow** [comment] 2018-05-02 05:17
Also, we would solve the dropdown form action on gridfield problem at the same time.

**Closed** 2018-05-03 05:44 UTC
Labels: affects/v4, change/minor, effort/medium, impact/high, type/bug, type/frontend
