### ISSUE TITLE
Upload field UI doesn't update on page publish

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-asset-admin#1080] opened 2020-04-21 21:30 UTC
# Upload field UI doesn't update on page publish

This is an UI only bug which is quite minor and can be remedied by user training and documentation. Still, it may be worth looking into especially if this is low effort fix.

Version `1.5.1`

## Test scenario

* page with has_one relation to Image (owns relation set up as well)
* both page and image are draft only
* publish the page via page edit form
* view the upload field for the image - it will be showing draft state for the image
* reload the page edit form and the image will be in the published state

This means that the publish operation works fine, it's just that the UI doesn't reflect this state immediately, without reloading the page.

**Comment by brynwhyman** [comment] 2020-04-28 23:22
Thanks for raising this issue. This looks like a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/960.

I'll close this in favour of the older issue.

**Closed by brynwhyman** 2020-04-28 23:22 UTC
