### ISSUE TITLE
Modal content overlapped on IE 11 and Windows 10

### ISSUE THREAD

**Issue by thejoshsmith** [silverstripe/silverstripe-asset-admin#909] opened 2019-01-28 07:57 UTC
We have a large client that is unfortunately forced to use a combo of IE 11 and Windows 10. They have reported that when editing an image, the modal is obscured by the form inputs underneath.

![screen shot 2019-01-28 at 4 24 58 pm](https://user-images.githubusercontent.com/5515179/51821521-5440fb00-233e-11e9-920d-7b7701a4ee27.png)

I had a quick look, and found the modal wrapper has inline styles of `position: relative;` and `z-index: 1050;`.

![screen shot 2019-01-28 at 4 25 31 pm](https://user-images.githubusercontent.com/5515179/51821666-d7fae780-233e-11e9-8753-f1ef74053265.png)

Removing _either_ of these inline styles corrects the display to what is expected.

![screen shot 2019-01-28 at 4 25 51 pm](https://user-images.githubusercontent.com/5515179/51821698-ec3ee480-233e-11e9-9848-be5ec43ffa1c.png)

Unfortunately I don't have the time to investigate further or fix, so any help would be much appreciated. Results can be reproduced using IE 11 on Windows 10 with Browser Stack.

Framework version is SS 4.2, running on PHP 7.2.

**Comment by dnsl48** [comment] 2019-01-30 22:38
Hi @thejoshsmith, thank you for reporting the issue.

I don't seem to be able to reproduce this on SS 4.3 with IE 11 and Windows 10.
It appears the issue might have already been fixed.
Could you try it on https://demo.silverstripe.com/admin/pages/ (which is 4.3) and give me a step-by-step description?

Cheers

**Comment by dnsl48** [comment] 2019-02-03 22:37
Seems to be a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8545

**Closed** 2019-02-04 20:33 UTC
Labels: feedback-required/author
