### ISSUE TITLE
Upload button not working on Chrome

### ISSUE THREAD

**Issue by JustinTBrown** [silverstripe/silverstripe-asset-admin#584] opened 2017-08-13 21:43 UTC
The upload button doesn't seem to work on Chome (60.0.3112.90) but it does on Firefox, Safari and Opera. My browser console shows no errors. There's just simply no response. I am able to add images via TinyMCE though in Chrome.

I'm on 4.0.0 beta 2 with the asset-admin module added via composer.

## Pull request
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/601

**Comment by tractorcow** [comment] 2017-08-14 21:59
Thanks for the report.

In order to help us get to the root cause of this issue, could you please try installing the chrome devtools for redux, and post us a screenshot of the redux log.

https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en to install.

Example log output when uploading:

![image](https://user-images.githubusercontent.com/936064/29293761-59308ca2-81a0-11e7-87f8-1caee80aed5c.png)

**Comment by JustinTBrown** [comment] 2017-08-17 00:19
There doesn’t seem to be any response?


Justin Brown
403.710.8249
justinbrown.io
On Mon, Aug 14, 2017 at 3:59 PM, Damian Mooyman <notifications@github.com> wrote:
Thanks for the report.

In order to help us get to the root cause of this issue, could you please try installing the chrome devtools for redux, and post us a screenshot of the redux log.

https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en [https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en] to install.

Example log output when uploading:

[https://user-images.githubusercontent.com/936064/29293761-59308ca2-81a0-11e7-87f8-1caee80aed5c.png]

**Comment by tractorcow** [comment] 2017-08-17 03:11
Redux doesn't track responses, it tracks local state changes to the client component as it is going through various operations. I would expect that even if the server did not respond (or receive requests) then you would still see activity in this log.

**Comment by tractorcow** [comment] 2017-08-23 01:57
Hi @JustinTBrown I'm sorry but I'm unable to reproduce the issue. Can you please include more information necessary to replicate the issues you've encountered?

**Comment by JustinTBrown** [comment] 2017-08-23 03:09
Sorry for the delay! I'm back in a big project and don't think I'll have time to look at this until mid-September. So sorry. I'm guessing it's simple to use the tool but it's taking me some time to get a handle on it (even though I'm guessing it's simpler than I think).





On Tue, Aug 22, 2017 at 7:57pm, Damian Mooyman < notifications@github.com [notifications@github.com] > wrote:
Hi @JustinTBrown [https://github.com/justintbrown] I'm sorry but I'm unable to reproduce the issue. Can you please include more information necessary to replicate the issues you've encountered?

**Comment by flamerohr** [comment] 2017-08-24 04:09
Hello, I've run into this intermittently, and it seems like a race condition between whether the upload button will mount first or the AssetDropzone will initialise first
Fixed by https://github.com/silverstripe/silverstripe-asset-admin/pull/601

**Closed** 2017-08-24 05:06 UTC
Labels: affects/v4, effort/easy, feedback-required/author, impact/high, type/bug, type/frontend
