### ISSUE TITLE
Easily edit image extra information from the UploadField

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-asset-admin#883] opened 2018-11-12 14:26 UTC
Hi,

In SS3, it was quite easy to edit extra fields on files. For instance, if I want to add a "Credits" field to an image, I would just create an ImageExtension with the text field and update the cms field.

In SS4, I'm not sure how I can easily do that : opening the file would open a very narrow edit form in the file browser.

Shouldn't there be a way to display the getCMSFields form for the file right from the upload field?

**Comment by kinglozzer** [comment] 2018-11-12 16:45
Thanks @lekoala, as it sounds very similar I’m going to close this one as a duplicate of #813

**Closed by kinglozzer** 2018-11-12 16:45 UTC
