### ISSUE TITLE
.htaccess blocking filenames that ends with multiple dots

### ISSUE THREAD

**Issue by jinjie** [silverstripe/silverstripe-asset-admin#811] opened 2018-07-17 08:20 UTC
Images uploaded and published with multiple dots causes 403 Forbidden by the following rule in htaccess

```
RewriteCond %{REQUEST_URI} !^[^.]*\.(?i:css|js|ace|arc|arj|asf|au|avi|bmp|bz2|cab|cda|csv|dmg|doc|docx|dotx|flv|gif|gpx|gz|hqx|ico|jpeg|jpg|kml|m4a|m4v|mid|midi|mkv|mov|mp3|mp4|mpa|mpeg|mpg|ogg|ogv|pages|pcx|pdf|png|pps|ppt|pptx|potx|ra|ram|rm|rtf|sit|sitx|tar|tgz|tif|tiff|txt|wav|webm|wma|wmv|xls|xlsx|xltx|zip|zipx)$
```
# Reproduce
- Upload an image with a filename with multiple dots. In my case, I have used `2018-04-24 02.54.59.jpg`
- Publish image

# Fix
- Rename the file to `2018-04-24.jpg`

**Comment by bummzack** [comment] 2018-07-17 08:41
Duplicate of: https://github.com/silverstripe/silverstripe-assets/issues/141

**Closed** 2018-07-17 08:51 UTC
