### ISSUE TITLE
Having to "Edit Original File" is unintuitive compared to SS3 inline editing

### ISSUE THREAD

**Issue by feejin** [silverstripe/silverstripe-asset-admin#813] opened 2018-07-24 15:57 UTC
When viewing image info the details (Title, Filename etc) appear to be form fields but are not editable, they can only be edited by clicking Edit Original File which opens in a new tab. 

It's more noticeable with the FocusPoint module when you want to just make a quick change as soon as you upload the image. Makes for quite a jarring user experience and I have to explain this to non-technical clients.

tl;dr make asset details editable without having to go via Edit Original File.

# User story
As a CMS user, I want to be able to stay in the current modal when editing a file, so that I can make quick updates to the file without loosing context of the area related to the file.

# Acceptance Criteria
- [x] 'Editing' a file keeps the user in the same modal
- [x] There is a button that initiates the file in a new editable state.
- [x] When editing the file, you can save/publish. 
- [x] When editing the file, the other actions are also available (archiving, unpublishing, replacing the file).
- [ ] A prompt will warn the user that edits will be applied globally.
- [x] There is a clear flow of inserting the image after editing. 
- [x] Editing a file in the modal might change its draft/live state. When you're done editing these changes should be reflected in the rest of the modal.

- [ ] This improvement is for the WYSIWYG modal only, and the uploadfield modal should be handled in a separate issue.

# Stretch Goal
* [x] Implement this feature in the Upload Field Modal or raise a separate issue for it.

# Suggested designs
* https://invis.io/WCMZMHHXRJV#/381953634_Files_Tiny_Insert_Files_new_File_start
* https://invis.io/WCMZMHHXRJV#/381953633_Files_Tiny_Insert_Files_existing_File_start

# Pull Requests
* [x] https://github.com/silverstripe/silverstripe-admin/pull/968
* [x] https://github.com/silverstripe/webpack-config/pull/39
* [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1038
* [ ] https://github.com/jonom/silverstripe-focuspoint/pull/78 (tweaks focus point module to work with the new image placement form)
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9425
* [x] https://github.com/silverstripe/cwp-recipe-kitchen-sink/pull/63

**Comment by maxime-rainville** [comment] 2018-07-27 05:50
That's kind of related to https://github.com/silverstripe/silverstripe-asset-admin/issues/756 and https://github.com/silverstripe/silverstripe-asset-admin/issues/785.

@ingo @clarkepaul Might be worthwhile having an epic for the insert media modal of the WYSIWY/UploadField.

**Comment by clarkepaul** [comment] 2018-07-30 08:08
The original concept was to have the details editable, but with a confirmation to ensure people know they are edit globally (eg information possibly used in other placements).

**Comment by feejin** [comment] 2018-07-30 10:52
@clarkepaul That would make sense, the global edit warning would be good as it's caught people (me) out in the past in SS3.

**Comment by ailionx** [comment] 2018-09-28 00:47
Hi, this issue is significantly affecting our product.  Wondering if there is any plan to solve this issue. Or is there any way to extend SilverStripe CMS to achieve this?

**Comment by clarkepaul** [comment] 2018-11-20 08:09
Thanks @lekoala for the detailed description, this will require some UI changes and it is on our radar to make the improvements. This one is best going through the UX team to review to look at the different options. Totally agree that editing should be possible when uploading a file directly. When it comes to files used in multiple locations we will advise on a solution.

**Comment by newleeland** [comment] 2019-01-16 21:52
### Potential Designs

Click from **Editing files**:
https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/folder/components/5c16d37d5d1e0fed52837855

**Comment by bscarola** [comment] 2019-02-22 00:46
The feedback link above isn't working for me. Is there any timeline for folding this into a release, or perhaps a temporary work-around? I've finally begun upgrading projects to SS4 and I agree that this is a major workflow issue for a lot of clients.

**Comment by clarkepaul** [comment] 2019-02-25 01:17
I've updated the link @bscarola. Looks like its basically turning the readonly fields into standard editable fields. When editing an existing file, I've flagged that there should probably be some sort of messaging to let a user know they might be editing a file which is used in several locations—for uploading that message wouldn't be required.

**Comment by lekoala** [comment] 2019-02-25 12:48
hey @clarkepaul is it me or this only covers tinymce/filemanager usage? What about regular upload fields directly visible through getCMSFields?

**Comment by clarkepaul** [comment] 2019-02-25 18:44
This should cover both ideally, I'd leave separating it into two issues to whoever picks it up. Thanks for mentioning it @lekoala

**Comment by neilcreagh** [comment] 2019-03-08 11:18
Just me two-cents to say that I think this should be very high priority. Editing an image title (or focus point) at the moment is a very awkward experience - especially for clients coming from SilverStripe 3 who could do this with one click from the uploadField before (and understood this to be an upgrade to their previous version).

**Comment by maxime-rainville** [comment] 2019-09-04 02:39
Just had a chat with @newleeland to talk over his design. The design introduces a somewhat different state in the insert modal to edit the detail of the image. This will probably require a bit more work than if we had just made the current read-only form editable, but it should provide a much nicer experience for the user.

This change will reuse functionality and UI elements uses elsewhere. Changes to the back end logic should be trivial ... juts minor tweaks to `FileFormFactory`. Most of the work will probably be in React.

Some things to keep in mind when implementing/testing this:
* When editing the file in the insert modal, you can save/publish. The other actions (archiving, unpublishing, replacing the file) will not be available.
* Users who might not have access to edit file, might still insert them. We should not show the button to trigger advanced editing.
* Editing a file in the modal, might change its draft/live state. When you're done editing and these change should be reflected in the rest of the insert modal.

**Comment by clarkepaul** [comment] 2019-09-04 03:00
I'd like to see how much more effort this would be as I think it would be really useful functionality.

> The other actions (archiving, unpublishing, replacing the file) will not be available.

**Comment by maxime-rainville** [comment] 2019-09-04 03:08
I don't think it would be technically difficult. It might add more edge case for us to consider.

The thing I'm not sure is if the user will be in a good head space to make those decision. e.g.: You decide to edit the "about us" page, you decide to replace a file without realising it's use on a bunch of other pages.

**Comment by clarkepaul** [comment] 2019-09-04 03:44
That's the same issue when in the files area, at least they have the "used on" tab. The way I see it is that as soon as you go away from the "Placement" view you've changed the mindset of what you are doing.

**Comment by neilcreagh** [comment] 2019-09-04 15:02
I see this as urgent, so I'd push for the fastest/simplest solution to be rolled into the next minor update - if that's simply changing the the current read-only form to be editable I think that should happen. Even better if there's a warning message about affecting all versions of the image.

**Comment by newleeland** [comment] 2019-09-09 00:44
### New Potential designs
https://invis.io/WCMZMHHXRJV#/381953634_Files_Tiny_Insert_Files_new_File_start
https://invis.io/WCMZMHHXRJV#/381953633_Files_Tiny_Insert_Files_existing_File_start

Comments on any edge cases are welcomed

**Comment by brynwhyman** [comment] 2019-09-16 00:24
Looking at the new designs... is the intention to remove all of the read-only tabs except from the 'Placement' tab, until the user edits the image?

I would have thought this information would still make sense for users without access to edit files to see?

**Comment by clarkepaul** [comment] 2019-09-16 01:39
We removed the tabs from the place view so there is no confusion with all of the actions... we can't have Insert mixed with Save/Publish but you do have a good point. We can't keep the preview tab when going to the edit view so there would be some inconsistency with what tabs are showing (unless we put placement into read-only) how about if the action at the top was "File details" (or "Details" for short) implying it is for both viewing and editing. We could leave the read-only data there but it is only a click away and you stay in context to the page.

**Comment by lekoala** [comment] 2019-09-16 08:10
@clarkepaul I see this issue is still only about usage of files inside TinyMCE. Was there another issue created to track usage in file uploads? It might be just me (but I don't think so!) but for me, it's also a matter to easily edit files attached through UploadFields. In SS3, it was really easy to do so, and more specifically adding new fields for an image ("credits" fields for instance).
For instance, how would a "image cropper" module be implemented with the current designs?
I wish there would be a way to have files simply scoped within the page or dataobject they belong with. Shared assets is really not my common use case : most of the time, my files only make sense in the context of a specific page or dataobject.

**Comment by clarkepaul** [comment] 2019-09-16 22:41
@lekoala Yup this caters to both TinyMCE and Uploadfield for editing, but placement details only apply to TinyMCE placement, we are considering how to attach ALT text field to UploadField items but included in this work.
Here are some of the issues for the file usage tab information https://github.com/silverstripe/silverstripe-asset-admin/issues/943 https://github.com/silverstripe/silverstripe-asset-admin/pull/998 https://github.com/dnadesign/silverstripe-elemental/pull/734

This will allow images to be edited from the context of the page. This issue doesn't go into how to add additional fields but I don't see this as being a problem UX wise.

**Comment by tractorcow** [comment] 2019-09-17 00:12
I tried restoring the edit feature when edit mode is "TYPE_SELECT", which restored the editability, but causes javascript errors when trying to save.

**Comment by tractorcow** [comment] 2019-09-17 00:25
It's because ACTION_TYPES.UPLOADFIELD_ADD_FILE is triggered when saving. UploadField treats any action as "insert", not only the actual "insert" action.

**Comment by tractorcow** [comment] 2019-09-17 00:47
This is what I would like to get working.

![image](https://user-images.githubusercontent.com/936064/65002650-06b6e400-d949-11e9-99ca-9972253d1de6.png)

This is the error I get when trying to save.

![image](https://user-images.githubusercontent.com/936064/65002676-24844900-d949-11e9-9795-71599b9d893a.png)

@unclecheese do you have any insights? Is there a "quick fix" to allow edit mode to work (when manually turned on)?

**Comment by newleeland** [comment] 2019-09-17 03:38
> Looking at the new designs... is the intention to remove all of the read-only tabs except from the 'Placement' tab, until the user edits the image?
> 
> I would have thought this information would still make sense for users without access to edit files to see?

We've rename the button to "File details" to accommodate this secondary flow of viewing and editing file details.

**Comment by newleeland** [comment] 2019-09-17 03:40
> Looking at the new designs... is the intention to remove all of the read-only tabs except from the 'Placement' tab, until the user edits the image?
> 
> I would have thought this information would still make sense for users without access to edit files to see?

We've rename the button to "File details" to accommodate this secondary flow of viewing and editing file details.

**Comment by tractorcow** [comment] 2019-09-19 00:30
I've tracked the issue to InsertMediaModal.js (used by uploadfield).

```js
  /**
   * Handles the insert form submission, does not continue the regular form submission within the
   * asset admin section.
   *
   * @param {object} data
   * @param {string} action
   * @param {function} submitFn
   * @param {object} file
   */
  handleSubmit(data, action, submitFn, file) {
    if (action === 'action_createfolder') {
      return submitFn();
    }
    return this.props.onInsert(data, file);
  }
```

Basically, any action other than "createFolder" is being treated as an insert.

**Comment by tractorcow** [comment] 2019-09-19 00:30
git diff to enable editable files during insert:


```diff
diff --git a/code/Forms/FileFormFactory.php b/code/Forms/FileFormFactory.php
index 2e4f884..d113b5c 100644
--- a/code/Forms/FileFormFactory.php
+++ b/code/Forms/FileFormFactory.php
@@ -66,7 +66,7 @@ class FileFormFactory extends AssetFormFactory
                 $tabs->unshift($this->getFormFieldLinkOptionsTab($record, $context));
                 break;
             case static::TYPE_SELECT:
-                $tabs->setReadonly(true);
+                //$tabs->setReadonly(true);
                 break;
         }

@@ -281,6 +281,8 @@ class FileFormFactory extends AssetFormFactory
         $actionItems = [];
         if ($type === static::TYPE_INSERT_MEDIA || $type === static::TYPE_SELECT) {
             $actionItems = array_filter([
+                $this->getSaveAction($record),
+                $this->getPublishAction($record),
                 $this->getInsertAction($record),
             ]);
         } elseif ($type === static::TYPE_INSERT_LINK) {
```

**Comment by tractorcow** [comment] 2019-09-19 00:35
This fixes it. :)

```
  handleSubmit(data, action, submitFn, file) {
    if (action === 'action_insert') {
      return this.props.onInsert(data, file);
    }

    // Standard form actions (e.g. publish)
    return submitFn();
  }
```

**Comment by tractorcow** [comment] 2019-09-19 00:41
Bugfix to the specific JS error at https://github.com/silverstripe/silverstripe-asset-admin/pull/1005

Note: This does not address the major issue, which is the negative user experience out of the box. :)

**Comment by tractorcow** [comment] 2019-09-25 21:04
By the way, I got the above working in my client project, and the client is very happy with the result.

In the upload field, you just need to click the "eye" icon beside any uploaded file, and you can immediately edit the file (as per the above screenshot).

You get all 3 menu actions (save, publish, insert) beside each file.

**Comment by clarkepaul** [comment] 2019-09-25 21:23
@tractorcow we choose not to do that for the Editor insert as the positioning is not part of the versioning for the file, but probably all good for the Upload Field though. 
Do you know if there any information for a file which is likely is added to an Upload Field which wouldn't be versioned? (e.g. do developers add positioning, additional fields like ALT text).

I'm thinking for a file to have an ALT text field by default included in the versioning so it can be used in the Upload Field instance. Trying to think of some edge cases for Upload Fields which you might have seen before.

**Comment by tractorcow** [comment] 2019-09-26 20:48
> @tractorcow we choose not to do that for the Editor insert as the positioning is not part of the versioning for the file, but probably all good for the Upload Field though.
Do you know if there any information for a file which is likely is added to an Upload Field which wouldn't be versioned? (e.g. do developers add positioning, additional fields like ALT text).

I would probably version everything regardless.

My use case is only for uploadfield assignment, I agree with you regarding the html editor media dialog. :) In the case of uploadfield though, the data for that record can only be stored on the file (unless we are somehow adding metadata to the uploadfield assignment; Possible future enhancement).

**Comment by maxime-rainville** [comment] 2019-10-15 22:46
How I'm thinking of approaching this:
* Update `FileFormFactory` so it doesn't return all the fields for the Insert Media and Insert Link form and returns a "Edit original" form action instead
* Update client side library to high jack the "Edit original" form action to
  * display it in a different spot
  * load the "fileEditForm" schema instead
* Make sure that backing out or saving the fileEditForm takes you back to the previous form.

**Comment by maxime-rainville** [comment] 2019-10-24 05:08
Just a quick update on where I'm at:
* I'm displaying the simplified form when inserting an image or a link
* You can click on a Detail button to edit the file
* You can click on a back button to return the insert media form

Next steps:
* Returning user to the insert media form when saving the image ... and other appropriate behaviour based on what action the user as selected.
* Storing the Insert Media form state before showing the Edit form ... and restoring it when you get back.

**Comment by neilcreagh** [comment] 2019-10-24 12:45
I think the UploadField issue is a much simpler approach, leaving everything behaving exactly as-is but allowing editing from the Uploadfield without the 'Edit Original File' button (And perhaps with a sentence explaining that this will edit the file anywhere it is currently used). 

Should the Uploadfield have a separate issue? The original post here says "This improvement is for the WYSIWYG modal only, and the uploadfield modal should be handled in a separate issue." but a couple of issues that have been opened about it have been closed as duplicates of this?

**Comment by maxime-rainville** [comment] 2019-10-29 03:11
@neilcreagh I'm half way through fixing this. From looking at the WYSIWYG modal, I don't think it's going to be terribly difficult to get the Upload field working. I'll add stretch goal to "Implement this  feature in the Upload Field Modal or raise a seperate issue for it".

Once I'm done, I'll be in a better position to know how difficult it's going to be.

**Comment by maxime-rainville** [comment] 2020-01-05 22:34
@silverstripeux I got this in something resembling a usable state.

https://youtu.be/dGOMiyzzekI 

Here's a few notes:
* The mock-ups have a "editing file x" header when editing the file in-modal. Adding this message only in the modal will make the logic somewhat inelegant. Would it be OK if I add it to the main asset area as well? Or if I drop it altogether?
* I've altered the way we display the title header field. This will also affect the asset-admin area.
* Saving/Publishing the original file doesn't currently automatically send you back to Placement form. Is that the behaviour we want? What about all the other actions?

# Warning when you're about to switch form

Right now, when you do an action in Asset-Admin or in the asset modal that will cause you to loose some changes, you don't get any warning. That's what in modal editing is doing right now. Maybe it's a bigger card, that need to be address somewhere else. Maybe we can address part of the issue here first.

If I start editing the placement information and then I edit the file details, what should happen?
  * Block the user from editing the details until they save the placement info?
  * Show some warning to the user?
  * Stash the form info and try reloading it once you're back from editing the file details?

We'll have the same problem with the edit detail form.

# Using/Abusing our new form editing powers
The way I've approach this, we could in theory get a form that opens another form, that opens another form, etc.

For example, we could use this to display "Add to campaign" form in the asset-admin panel instead of using a separate modal. Or we could display delete/unpublish confirmation message for the file you are currently editing there.

**Comment by clarkepaul** [comment] 2020-01-12 23:07
Thanks @maxime-rainville I'll have a look and get back to you this week.

**Comment by maxime-rainville** [comment] 2020-01-12 23:18
@sachajudd Already gave me some feedback and I made a fair bit of progress since I wrote that message. Maybe hold off looking into it until tomorrow. I'll try to get my updates into a presentable state and you can review the greatest and latest.

**Comment by lekoala** [comment] 2020-01-13 13:25
@maxime-rainville any update on dealing with UploadFields and allowing editing files from there easily in a customisable fashion?

**Comment by martinviolet88** [comment] 2020-01-16 13:46
@maxime-rainville any updates?

**Comment by brynwhyman** [comment] 2020-01-26 22:32
Hey @lekoala , @martinviolet88 you could check the related pull requests (in the original description) for some more detail on the progress of the issue. Currently the focus is still being spent on the WYSIWYG modal, before the UploadField modal is looked at.

There's a few related PRs, but if you would like to check these out and provide any feedback/ test notes, that would be much appreciated!

**Comment by emteknetnz** [comment] 2020-04-17 03:45
Ran it all of the combined PR's through travis cwp-recipe-kitchen-sink - there was a single regression

https://travis-ci.org/github/creative-commoners/cwp-recipe-kitchen-sink/builds/676011738

Note: ignore the failure in 'recipe_content_blocks' that's an existing failure

Note: this is a kinda special travis build, you can't restart the build to get the latest changes, you need to run composer update on your local and recommit the composer.lock file

**Comment by maxime-rainville** [comment] 2020-05-04 02:10
Everything is done. There's a related PR against the focuspoint module. I've let the module maintainer that it's coming.

**Closed by maxime-rainville** 2020-05-04 02:10 UTC
Labels: affects/v4, change/minor, effort/medium, impact/high, type/UX, type/enhancement

**Comment by maxime-rainville** [comment] 2020-05-11 23:04
FYI The related focus point PR has been merged. https://github.com/jonom/silverstripe-focuspoint/pull/78
