### ISSUE TITLE
Uploading a super large file shows wrong error message

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-asset-admin#454] opened 2017-04-28 03:33 UTC
Instead "File larger 2 MB", it should "Server responded with an error". Again the same as https://github.com/silverstripe/silverstripe-asset-admin/issues/453 the message should show right away right not after the file finishes uploading.

## Test

https://hiptest.net/app/projects/47032/test-runs/77619/folder-snapshots/492547/scenario-snapshots/2172491/test-snapshots/2484774

**Comment by chillu** [comment] 2017-07-07 03:39
Duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/532

**Closed by chillu** 2017-07-07 03:39 UTC
Labels: affects/v4, impact/low, type/bug
