### ISSUE TITLE
Shift-click on file should be the same as clicking the tick

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#547] opened 2017-07-14 04:36 UTC
In other apps, a faster way of selecting many items to hold down shift and clicking them.

I think that shift-clicking anywhere on the file should have the same behaviour as clicking the tickbox.

**Comment by clarkepaul** [comment] 2017-07-16 22:14
This is a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/424 so closing.

**Closed by clarkepaul** 2017-07-16 22:14 UTC
