### ISSUE TITLE
Max file number validation message returns "Bobby"

### ISSUE THREAD

**Issue by jcop007** [silverstripe/silverstripe-asset-admin#916] opened 2019-02-22 00:25 UTC
Max file number validation message is returning "Bobby" rather than a meaningful message.

https://github.com/silverstripe/silverstripe-asset-admin/blob/1.3.1/code/Forms/UploadField.php#L324

public function validate($validator)
    {
        $maxFiles = $this->getAllowedMaxFileNumber();
        $count = count($this->getItems());
        if ($maxFiles < 1 || $count <= $maxFiles) {
            return true;
        }
        $validator->validationError($this->getName(), _t('', 'Bobby'));
        return false;
    }

**Comment by maxime-rainville** [comment] 2019-02-22 01:08
I've confirmed the behaviour. I'm setting the impact to high because of the destructive nature of the issue.

**Comment by maxime-rainville** [comment] 2019-02-22 01:11
@bergice fixed it already. https://github.com/silverstripe/silverstripe-asset-admin/commit/17710cc242e2ca37cf4422f7606de61cbc6b04e9#diff-67dd240acb2dd7bb559ec942bba7678f

But only on the `1` branch.

**Comment by chillu** [comment] 2019-02-24 21:37
Non critical bugs only get fixed on the current release branch, so closing

**Closed by chillu** 2019-02-24 21:37 UTC
Labels: affects/v4, effort/easy, impact/low, type/bug

**Comment by jcop007** [comment] 2019-02-24 22:00
Hi
The bug IS in the current release branch (4.3).  This fix is only in 4.1.
Cheers,
Jonathan

**Comment by maxime-rainville** [comment] 2019-02-25 00:22
The fix was made in the 1.3 branch, but not in time for the 4.3.1 release. It should be part of the 4.3.2 release.

**Comment by jcop007** [comment] 2019-02-25 00:31
Great.  Thanks.
