### ISSUE TITLE
Canvas previews cause excessive memory use

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#248] opened 2016-09-12 23:42 UTC
`AssetDropzone.js` creates `<canvas>` on upload with the full sized images, which causes  ~200MB of memory use for a 2700x3500px image in Chrome, so roughly the raw byte size at 16 bits. With 100% CPU for a few seconds.

Find a way to create a smarter preview, for example emulating what our 3.x upload previews do: https://github.com/blueimp/JavaScript-Load-Image

This is different from images being shown in full size after upload: https://github.com/silverstripe/silverstripe-asset-admin/issues/237

**Comment by sminnee** [comment] 2016-09-21 21:26
Quick google dug up this, haven't looked into it: https://github.com/caike/React-Thumb-Preview

**Comment by flamerohr** [comment] 2016-09-22 00:12
I believe this is caused by the logic loading the full image to data-url, when it should've drawn the image to a canvas the same size as the thumbnail preview then load the data-url from that.

For future note:
http://stackoverflow.com/questions/23104582/scaling-an-image-to-fit-on-canvas

**Comment by flamerohr** [comment] 2016-09-22 03:51
sort of addressed in https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/4.0/speedup-upload-preview

**Comment by flamerohr** [comment] 2016-09-22 04:31
Pull request made:
https://github.com/silverstripe/silverstripe-asset-admin/pull/270

**Closed** 2016-09-23 00:09 UTC
Labels: affects/v4, impact/high, type/bug
