### ISSUE TITLE
File 'Details' link not visible if file is not on current page

### ISSUE THREAD

**Issue by swordfox** [silverstripe/silverstripe-asset-admin#1171] opened 2020-12-16 23:30 UTC
If you click view icon on an upload field, when the modal loads, the 'Details' link in top right is not visible is the file you are editing is not on the current page.

In the example screenshots below, the image is on page 6, 1st screenshot shows when I first click the view icon and the modal loads on page 1.

![Screen Shot 2020-12-17 at 12 28 44 PM](https://user-images.githubusercontent.com/549500/102418892-827b7100-4063-11eb-93f8-d9b927ab0f1b.png)

The second screenshot is once I've navigated to page 6 and the details link appears.

![Screen Shot 2020-12-17 at 12 26 19 PM](https://user-images.githubusercontent.com/549500/102418912-90c98d00-4063-11eb-8d2e-3f9a5395ee0e.png)

**Comment by bergice** [comment] 2021-01-05 00:13
Duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/1136

**Closed by bergice** 2021-01-05 00:13 UTC
