### ISSUE TITLE
Drag over "parent file" button too subtle

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-asset-admin#548] opened 2017-07-14 04:40 UTC
You can drag a file onto the parent folder button to move it up a folder. This is great.

However, the animation on the icon is a little too subtle. Perhaps it could grow more, or change colour?

**Comment by clarkepaul** [comment] 2017-07-16 22:13
This is a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/424 so closing.

**Closed by clarkepaul** 2017-07-16 22:13 UTC
