### ISSUE TITLE
Asset-admin modal doesn't show scrollbars (windows)

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-asset-admin#1179] opened 2021-02-25 03:36 UTC
![image](https://user-images.githubusercontent.com/936064/109099083-537e2b80-7787-11eb-9686-2a2051b5dce6.png)

https://www.whatsmybrowser.org/b/JZAJT

I was expecting to see a scrollbar, but the `<fieldset />` doesn't have one.

Apparently this occurs on windows version of Chrome (but not OSX).

**Comment by Cheddam** [comment] 2021-02-28 21:06
Hey @tractorcow, this is a duplicate of #1163, which we opted to close because it's an issue with that specific release of Google Chrome. Updating to Chrome 88 should resolve this problem for you - if it doesn't, feel free to reopen and we can take another look.

**Closed by Cheddam** 2021-02-28 21:06 UTC

**Comment by tractorcow** [comment] 2021-04-18 21:07
thanks @Cheddam that's what I thought.

It's just good that I can go back to my client and tell them that. :)
