### ISSUE TITLE
Asset Admin - Pagination - Cannot access 'page dropdown'.

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-asset-admin#617] opened 2017-09-06 00:04 UTC
When viewing a 'Folder (or) Search Results' with a large number of files, attempting to utilize the 'pagination - dropdown field' to navigate to a specific page does not work, i.e. the dropdown cannot be clicked-on.

Note - Can keyboard-tab to the dropdown and access it, however selecting a specific page navigates to the incorrect page, i.e. selecting 'page 3' from the dropdown opens 'page 2'.

STR - 
1. Upload a large number of files to 'Assets'. (Around 120)
2. Click the 'Page Selector/dropdown'.

Note - SS4 project.

## Pull request
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/623

**Comment by tractorcow** [comment] 2017-09-07 01:08
Issue was caused by <SelectableGroup> missing a `preventDefault={false}` in Gallery.js.

**Comment by flamerohr** [comment] 2017-09-07 01:18
will be fixed with https://github.com/silverstripe/silverstripe-asset-admin/issues/525

**Comment by flamerohr** [comment] 2017-09-08 02:01
Found it broke in another part

**Closed** 2017-09-08 02:55 UTC
Labels: affects/v4, impact/high, type/bug
